In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Create the model
model = Sequential([
    Dense(units=2, input_dim=2, activation='tanh'),  # Hidden layer
    Dense(units=4, activation='tanh'),
    Dense(units=1, activation='sigmoid')               # Output layer
])

# Compile the model
model.compile(optimizer='sgd', loss='mse', metrics=['accuracy'])

# Example Dataset (XOR-like, single input neuron case)
X = tf.constant([[0.0, 1.0], [1.0, 0.0], [0.0, 0.0], [1.0, 1.0]])  # Inputs
y = tf.constant([[0], [0], [1], [0]])  # Corresponding outputs

# Train the model
model.fit(X, y, epochs=1000, verbose=0)  # Training with 1000 epochs

# Test the model
for x in X:
    # Reshape single input to a batch with one sample
    x_batch = tf.constant([x.numpy()])  # Add extra dimension for batch
    pred = model.predict(x_batch, verbose=0)
    print(f"Input: {x.numpy()}, Predicted Output: {round(pred[0][0])}")



c:\users\emand\appdata\local\programs\python\python39\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Input: [0. 1.], Predicted Output: 0
Input: [1. 0.], Predicted Output: 0
Input: [0. 0.], Predicted Output: 1
Input: [1. 1.], Predicted Output: 0


In [3]:
# Get weights of the first Dense layer (hidden layer)
hidden_layer_weights = model.layers[0].get_weights()
hidden_layer_kernel = hidden_layer_weights[0]  # Weights connecting input to the layer
hidden_layer_bias = hidden_layer_weights[1]    # Bias of the layer

# Get weights of the second Dense layer (output layer)
output_layer_weights = model.layers[1].get_weights()
output_layer_kernel = output_layer_weights[0]  # Weights connecting hidden layer to output
output_layer_bias = output_layer_weights[1]    # Bias of the output layer

for i in range(len(model.layers)):
    layer = model.layers[i].get_weights()
    layer_weights = layer[0]
    layer_biases = layer[1]
    
    print(f"Layer {i} Weights: {layer_weights}")
    print(f"Layer {i} Biases: {layer_biases}")


Layer 0 Weights: [[ 0.2210936 -0.8902752]
 [ 0.8239516 -0.6125957]]
Layer 0 Biases: [-0.13039072  0.25153247]
Layer 1 Weights: [[ 0.68853396 -0.5035588  -0.0798488  -0.33602378]
 [ 0.01691409 -0.54968256  0.6834315   1.0586222 ]]
Layer 1 Biases: [ 0.06435737 -0.05740328 -0.03218207  0.10515415]
Layer 2 Weights: [[-0.7879031]
 [ 0.7047428]
 [ 1.152326 ]
 [ 1.1635352]]
Layer 2 Biases: [-0.1317011]


In [4]:
import math

def sigmoid(x):
    return 1/(1+np.exp(-x))

def mean_squared_loss(pred, actual):
    return (pred - actual) ** 2

def deriv_sigmoid(y):
    return y(1 - y)

def deriv_mean_squared_loss(pred, actual):
    return 2*(pred - actual)

In [39]:
import numpy as np

class Model:
    def __init__(self, layers, activation, deriv_activation, loss, deriv_loss):
        self.weights, self.biases = self._init_layers(layers)
        self.activation = activation
        self.deriv_activation = deriv_activation
        self.loss = loss
        self.deriv_loss = deriv_loss
        
    def _init_layers(self, layers):
        all_weights = []
        all_biases = []
        for i in range(len(layers) - 1):
            weights = np.random.uniform(low=0, high=1, size=(layers[i + 1], layers[i]))
            biases = np.random.uniform(low=0, high=1, size=(layers[i + 1], 1))
            all_weights.append(weights)
            all_biases.append(biases)
            
        return all_weights, all_biases
    
    def _forward_pass(self, x_initial):
        current_input =  np.array(x_initial).reshape(-1, 1)
        values = [current_input]
        
        for i in range(len(self.weights)):
            z = np.matmul(self.weights[i], current_input) + self.biases[i]
            output = self.activation(z)
            values.append(output)
            current_input = output
        
        return values
    
    def _backward_pass(self, inputs, outputs):
        pass
    
    
example_model = Model([1, 2, 2, 2], sigmoid, deriv_sigmoid, mean_squared_loss, deriv_mean_squared_loss)
example_model._forward_pass(np.array([1]).reshape(-1, 1))          

[array([[1]]),
 array([[0.51464568],
        [0.58360184]]),
 array([[0.84835177],
        [0.82354412]]),
 array([[0.82631072],
        [0.78178019]])]